import yfinance as yf
from pydantic import BaseModel
from datetime import date, timedelta
from pathlib import Path
import json
from etl.transform_config import START_YEAR


def load_halal_universe() -> list[dict]:
    """loads halal stock list from JSON generated by extract_halal_universe.py"""
    universe_path = Path(__file__).parent.parent / "halal_universe.json"
    with open(universe_path) as f:
        data = json.load(f)
    return data["compliant"]


# Pydantic models
class PriceRecord(BaseModel):
    date: date
    close: float
    volume: float

class PriceResponse(BaseModel):
    ticker: str
    name: str
    records: list[PriceRecord]


def fetch_prices(ticker: str, start: str = f"{START_YEAR}-01-01", end: str | None = None) -> PriceResponse:
    end = end or str(date.today() + timedelta(days=1))
    raw = yf.download(
        ticker,
        start=start,
        end=end,
        auto_adjust=True, #auto split
        progress=False,   #progress bar
        multi_level_index=False,  #dont need the complicated stuff  
    )

    if raw.empty:
        raise ValueError(f"No data returned for: {ticker}")

    
    name = yf.Ticker(ticker).info.get("longName", ticker)

    records = [
        PriceRecord(
            date=row_date.date(),
            close=round(float(row["Close"]), 4),
            volume=float(row["Volume"]) if float(row["Volume"]) > 0 else 0.0,
        )
        for row_date, row in raw.iterrows()
    ]

    return PriceResponse(ticker=ticker, name=name, records=records)

def fetch_all_prices() -> list[PriceResponse]:
    """Fetch prices the universe"""
    universe = load_halal_universe()
    results = []

    for stock in universe:
        ticker = stock["ticker"]
        name = stock["name"]
        print(f"  Fetching {ticker:6} ({name})...")

        try:
            result = fetch_prices(ticker)
            results.append(result)
            print(f"           {len(result.records)} days of trading")
        except Exception as e:
            print(f"           Erreur: {e}")

    return results


if __name__ == "__main__":
    choice = input("Fetch (1) specific ticker or (2) all the halal universe ? ")

    if choice == "1":
        ticker = input("Ticker : ").upper()
        result = fetch_prices(ticker)
        print(f"Ticker  : {result.ticker}")
        print(f"Days    : {len(result.records)}")
        print(f"First   : {result.records[0]}")
        print(f"Last    : {result.records[-1]}")

    elif choice == "2":
        all_prices = fetch_all_prices()
        print(f"Total stocks fetched : {len(all_prices)}")
        for r in all_prices:
            print(f"  {r.ticker:6} → {len(r.records)} days, "
                  f"Last close: {r.records[-1].close}")